variables:
  BUILD_SOURCE: "github.com/wmark/semver"

stages:
- prerequisites
- test

.go_template: &use_dependencies
  before_script:
  - mkdir -p _vendor-cache /var/go/ours
  - ln -s "$(pwd -P)/_vendor-cache" /var/go/theirs
  - export GOPATH=/var/go/theirs:/var/go/ours:/usr/share/gocode

  - export GODIR=/var/go/ours/src/$BUILD_SOURCE
  - mkdir -p "$(dirname "$GODIR")"
  - ln -sfv "$(pwd -P)" "$GODIR"

  - cd "$GODIR"
  cache:
    key: "$CI_PROJECT_NAME-$CI_BUILD_REF_NAME"
    policy: pull
    paths:
    - _vendor-cache/

# This very first job will download any dependencies.
get_dependencies:
  stage: prerequisites
  <<: *use_dependencies
  script:
  - go get -d -t ./...
  cache:
    key: "$CI_PROJECT_NAME-$CI_BUILD_REF_NAME"
    policy: pull-push
    paths:
    - _vendor-cache/

vet:
  stage: test
  <<: *use_dependencies
  script:
  - diff <(echo -n) <(gofmt -s -d $(find . -type f -name '*.go' -not -path "./_*"))
  - go vet ./...

lint:
  stage: test
  <<: *use_dependencies
  script:
  - ineffassign .
  - golint ./...

unittests:
  stage: test
  <<: *use_dependencies
  script:
  - go test -v ./...
